### ISSUE TITLE
RobotReviewer

### ISSUE THREAD

**Issue by sanjaschreiber** [ijmarshall/robotreviewer#1]
Hi @ijmarshall ,

I love RobotReviewer, and we were thinking of testing it against a sample of our RoB assessments, but it seems as though the [Demo website](https://robot-reviewer.vortext.systems/) has some issues. I have tried Google Chrome, Safari, Fire Fox, and while all are successful in uploading a PDF, the RoB does not work.

I appreciate your help and I congratulate you on this truly amazing work!

Sanja Schreiber Ph.D.
Postdoctoral fellow 
Alberta Research Centre for Health Evidence - ARCHE
Department of Pediatrics, University of Alberta

**Comment by bwallace** [comment]
HI Sanja,

First, thanks for the kind words re:RR! We're indeed having some issues
with the demo site right now -- sorry about that, we just noticed this last
week. We're trying to get things back to functioning ASAP. In the meantime,
if sufficiently motivated it shouldn't be too hard to run locally and play
with, although I know that's a bit of a pain. (Here's the link to the code:
https://github.com/ijmarshall/robotreviewer; if you are interested in this
route, let us know and we can help!)

Anyway, we'll get back to you as soon as we've got an update.

best,
-byron

best,
-byron

On Mon, Apr 4, 2016 at 1:16 PM, Sanja S. <notifications@github.com> wrote:

> Hi @ijmarshall <https://github.com/ijmarshall> ,
>
> I love RobotReviewer, and we were thinking of testing it against a sample
> of our RoB assessments, but it seems as though the Demo website
> <https://robot-reviewer.vortext.systems/> has some issues. I have tried
> Google Chrome, Safari, Fire Fox, and while all are successful in uploading
> a PDF, the RoB does not work.
>
> I appreciate your help and I congratulate you on this truly amazing work!
>
> Sanja Schreiber Ph.D.
> Postdoctoral fellow
> Alberta Research Centre for Health Evidence - ARCHE
> Department of Pediatrics, University of Alberta
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ijmarshall/robotreviewer/issues/1>
>



-- 
byron

**Comment by sanjaschreiber** [comment]
Hi @bwallace Byron, 

many thanks for your reply. I am not really that technically savvy, but I'll give it a try to run it locally. :)

By the way, I actually noticed this issue with the website some time ago, but didn't think too much of it. I should've let you know right away. 

All the best!
Sanja

**Comment by bwallace** [comment]
Hi Sanja,

Should be back up and functional now! Let us know if you have any issues
(and indeed any thoughts you have on the tool).

best,
-byron


On Mon, Apr 4, 2016 at 1:38 PM, Sanja S. <notifications@github.com> wrote:

> Hi @bwallace <https://github.com/bwallace> Byron,
>
> many thanks for your reply. I am not really that technically savvy, but
> I'll give it a try to run it locally. :)
>
> By the way, I actually noticed this issue with the website some time ago,
> but didn't think too much of it. I should've let you know right away.
>
> All the best!
> Sanja
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ijmarshall/robotreviewer/issues/1#issuecomment-205441292>
>



-- 
byron
