### ISSUE TITLE
error IO when launching robotreviewer

### ISSUE THREAD

**Issue by gmadevs** [ijmarshall/robotreviewer#1]
I'm working on a mac, I followed all the instructions but when launching robotreviewer for the first time this error appears

IOError: [Errno 2] No such file or directory: '[path].../robotreviewer/data/pubmed/pubmed_title_hash_2016_08_18.npz'

are there any file to update before launching robotreviewer? the file in the repository has the date 2016/07/24

**Comment by ijmarshall** [comment]
hi, and thanks for letting us know. I've changed the reference to use the data in the repo for the moment. We will be moving to a newer data file soonish once we've ironed out some kinks.

I've pushed a fix; hope this works :)

**Comment by gmadevs** [comment]
Yes, thanks!
