### ISSUE TITLE
Demo website down

### ISSUE THREAD

**Issue by wooooooooooooooowastaken** [ijmarshall/robotreviewer#20]
> We're sorry! We're having some technical problems, and our RobotReviewer demo website is down at the moment. We're working to get it up and running as soon as possible, but we need to get a new server. 
http://www.robotreviewer.net/status/

Website would be extremely helpful in avoiding manual intallation.  Thanks for all of the work you've done in making this program.

**Comment by bwallace** [comment]
We are aware that the demo website is down, so this isn't really an issue as such. We're *hoping* to get it back up by end of week or so, but no promises :). Thanks for your interest, regardless -- do keep checking back!
