### ISSUE TITLE
problem in installing 

### ISSUE THREAD

**Issue by AdelehAsadi** [ijmarshall/robotreviewer#22]
I install anaconda in windows and then i wanted to add  this code
conda env create -f robotreviewer_env_local.yml
i got this error 
ResolvePackageNotFound
  - spacy=0.101.0   
   - ptyprocess=0.5.1
how can i solve this problem

thank you for helping.

**Comment by ijmarshall** [comment]
multiple updates to environment to fix issues and verified working linux/mac/windows(docker)
