### ISSUE TITLE
Error creating conda env on OSX

### ISSUE THREAD

**Issue by johnc1231** [ijmarshall/robotreviewer#27]
I get this error when trying to create the conda env on OSX.
```
ResolvePackageNotFound:
  - binutils_impl_linux-64 2.31.1 h6176602_1
```
It seems clear to me that that this is a linux specific package, so I am not surprised by the error. Is the intention to only support linux?

**Comment by ijmarshall** [comment]
Thanks - we've fixed up the environment so shouldn't have this issue any further.
