### ISSUE TITLE
UnpicklingError

### ISSUE THREAD

**Issue by restingsheep** [ijmarshall/robotreviewer#3]
I was trying to run robotreviewer but I received the following error:

preprocessor = pickle.load(open(vectorizer_loc, 'rb'))
_pickle.UnpicklingError: invalid load key, 'v'.

Would you mind of helping me with this? Many thanks.

**Comment by yinfeiy** [comment]
You will need the git lfs to download the entire model file. Original git seems not be able to handle very large file. 

https://github.com/git-lfs/git-lfs/wiki/Installation

**Comment by restingsheep** [comment]
I have installed 'git-lfs', updated it and the same error still came up:/

**Comment by bwallace** [comment]
what version of Python are you using?

**Comment by restingsheep** [comment]
Python 3.6. I am using OS X under anaconda. Presumably if this is resulted from the version of Python, I should have the same problem as yinfeiy's latest issue.

**Comment by restingsheep** [comment]
Below is the description:

(root) MacBook-Air-7:robotreviewer3 restingsheep$ python -m robotreviewer
[INFO] robotreviewer.app 2017-07-30 19:24:57,199: Welcome to RobotReviewer :)
[INFO] robotreviewer.textprocessing.pdfreader 2017-07-30 19:24:57,636: Attempting to start Grobid sever...
[INFO] robotreviewer.textprocessing.pdfreader 2017-07-30 19:24:57,636: Launching Grobid process... (from /Users/restingsheep/grobid-grobid-parent-0.4.1)
[INFO] robotreviewer.textprocessing.pdfreader 2017-07-30 19:24:57,640: Success! :)
[DEBUG] robotreviewer.textprocessing.tokenizer 2017-07-30 19:24:58,051: Loading spacy.io data for tokenization
Using TensorFlow backend.
/Users/restingsheep/robotreviewer3/robotreviewer/app.py:76: FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
  csrf = CsrfProtect()
[INFO] robotreviewer.app 2017-07-30 19:25:18,630: Loading the robots...
Traceback (most recent call last):
  File "/Users/restingsheep/anaconda/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/restingsheep/anaconda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/restingsheep/robotreviewer3/robotreviewer/__main__.py", line 1, in <module>
    from robotreviewer import app
  File "/Users/restingsheep/robotreviewer3/robotreviewer/app.py", line 84, in <module>
    bots = {"bias_bot": BiasRobot(top_k=3),
  File "/Users/restingsheep/robotreviewer3/robotreviewer/robots/rationale_robot.py", line 87, in __init__
    preprocessor = pickle.load(open(vectorizer_loc, 'rb'))
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by restingsheep** [comment]
I re-installed the robotreviewer3 and got the latest error:

    self.vectorizer = pickle.load(f, encoding="latin")
ImportError: No module named 'pandas.indexes'

**Comment by bwallace** [comment]
Is pandas installed?

________________________________

**Comment by restingsheep** [comment]
Yes, mine is updated to 0.20.3. I have tried to downgrade it to version 0.20.2, but still got the same error.

**Comment by bwallace** [comment]
Hmm can you run  `from pandas import indexes`? 

Perhaps try downgrading to 0.19.1

**Comment by restingsheep** [comment]
It came up with a different error after installed 0.19.1...lol

File "/Users/restingsheep/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3020, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'left token input' is not a valid scope name

**Comment by bwallace** [comment]
Progress :). So but you're getting a tensorflow error -- however the assumption is that you're using the theano backend for keras. This is a flag you have to set; see [here](https://keras.io/backend/).

**Comment by restingsheep** [comment]
Thank you! I swear I have changed it but realised that I have to rewrite the .json file! However, another problem with HDF5 utilities:

  File "/Users/restingsheep/anaconda/lib/python3.5/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1490026355393/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1490026355393/work/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/Users/ilan/minonda/conda-bld/h5py_1490026355393/work/h5py/h5f.c:2123)
OSError: Unable to open file (File signature not found)
