### ISSUE TITLE
Trial registration

### ISSUE THREAD

**Issue by badgettrg** [ijmarshall/robotreviewer#8]
Great project. If your framework is a [Cochrane Risk of Bias table](http://handbook-5-1.cochrane.org/chapter_8/table_8_5_a_the_cochrane_collaborations_tool_for_assessing.htm), then when you develop assessment of 'Reporting bias', consider parsing the pdf for evidence of trial registration and,  if evidence of registration not found, alert users that at risk of selective reporting. Unfortunately, this still does not catch when a trial was registered and the publication changes outcomes; however, you could create a link to the trial registration and suggest users compare planned/reported outcomes.

**Comment by bwallace** [comment]
Thanks for the suggestion! This is something we will consider adding -- we already look up studies on CT.gov, so this would be a natural extension. 

I'm closing this, however, since it's not an issue, at such.
