### ISSUE TITLE
RR3 killed

### ISSUE THREAD

**Issue by jdoedoej** [ijmarshall/robotreviewer#9]
Whenever I run RR3, this is printed to the terminal:

```
[INFO] robotreviewer.app 2017-09-03 14:59:33,678: Loading the robots...
loading model architecture from file: robotreviewer/data/keras/models/RSG.json
ok!
Killed
```

Any ideas on why it is killed?

**Comment by joelkuiper** [comment]
Very likely because you are running out of memory. If you are using Docker for Mac you need to go into settings and give it more memory, it's quite an intensive process; I have mine set to 8GB.
